In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\Ernie\Documents\GitHub\Citi_Bike_Viz\Resources\updated_file.csv')

In [4]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_date,start_time,end_date,end_time
0,8886EF8C9BD07586,electric_bike,2024-05-06 13:57:24,2024-05-06 14:09:04,W 34 St & 11 Ave,6578.01,1 Ave & E 44 St,6379.03,40.756185,-74.002590,40.750020,-73.969053,member,2024-05-06,13:57:24,2024-05-06,14:09:04
1,7DA49CAE12D5AD44,electric_bike,2024-05-26 10:27:04,2024-05-26 10:36:41,E 95 St & 3 Ave,7365.13,3 Ave & E 62 St,6762.04,40.784904,-73.950526,40.763126,-73.965269,member,2024-05-26,10:27:04,2024-05-26,10:36:41
2,24EE0168B758EECA,classic_bike,2024-05-13 11:51:21,2024-05-13 11:56:29,Norfolk St & Broome St,5374.01,Division St & Bowery,5270.08,40.717227,-73.988021,40.714193,-73.996732,member,2024-05-13,11:51:21,2024-05-13,11:56:29
3,84D7596D27A0BB58,classic_bike,2024-05-30 06:57:31,2024-05-30 07:03:39,Broadway & W 41 St,6560.01,E 47 St & Park Ave,6584.12,40.755136,-73.986580,40.755103,-73.974987,member,2024-05-30,06:57:31,2024-05-30,07:03:39
4,BEA997A296AC0F88,electric_bike,2024-05-11 00:39:24,2024-05-11 00:43:15,E 2 St & Ave B,5515.02,Mott St & Prince St,5561.04,40.722165,-73.983829,40.723180,-73.994800,member,2024-05-11,00:39:24,2024-05-11,00:43:15

In [ ]:
date_length = df(['start_date']-['end_date'])